default:
  image: quay.io/centos/centos:7
  before_script:
    - yum -y install make wget which gcc curl
    - wget --no-verbose --directory-prefix=/tmp/ https://go.dev/dl/go1.19.12.linux-amd64.tar.gz
    - tar -C /usr/local -xzf /tmp/go1.19.12.linux-amd64.tar.gz
    - export PATH=$PATH:/usr/local/go/bin:${HOME}/go/bin/
    - go version

golint:
  script:
    - make golint
  only:
    - merge_requests

compile-testcmd:
  script:
    - make install
    - make testcmd-bin
  only:
    - merge_requests

compile-all-test-suites:
  script:
    - make install
    - export PATH=$PATH:/usr/local/go/bin:~/go/bin
    - ginkgo build -r ./test/
  only:
    - merge_requests

dry-run-tests:
  script:
    - make install
    - export PATH=$PATH:/usr/local/go/bin:~/go/bin
    - ginkgo -dry-run -v --keep-going -require-suite -r test/
  only:
    - merge_requests
