run:
  build-tags:
    - codeanalysis
  go: "1.18"
  timeout: 15m0s
  skip-dirs-use-default: true
  fast: false
  skip-files:
    - test/tools.go
linters-settings:
  revive:
    rules:
      - name: indent-error-flow
      - name: var-naming
      - name: increment-decrement
  wsl:
    strict-append: false
  gocognit:
    min-complexity: 36
  gofmt:
    simplify: true
  funlen:
    lines: 175
    statements: 85
  unused:
    check-exported: true
  stylecheck:
    dot-import-whitelist:
      - github.com/onsi/gomega
      - github.com/onsi/ginkgo/v2
    # Select the Go version to target. The default is '1.13'.
    # https://staticcheck.io/docs/options#checks
    checks: [ "all", "-ST1001"]

linters:
  enable:
    - asciicheck
    - bidichk
    - deadcode
    - depguard
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    - gosimple
    - govet
    - ifshort
    - ineffassign
    - ireturn
    - lll
    - makezero
    - misspell
    - nakedret
    - nilnil
    - nolintlint
    - predeclared
    - promlinter
    - revive
    - staticcheck
    - stylecheck
    - tenv
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - varnamelen
    - wsl
    - nlreturn

output:
  format: colored-line-number
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  include:
    - EXC0002 # disable excluding of issues about comments from golint
  exclude-rules:
    # Exclude some linters from running on tests files.
#    - path: cnf-gotests/test/testcmd_suite_test.go
#      linters:
#        - goanalysis_metalinter
    - path: test/parameters/init.go
      linters:
        - gochecknoinits
    - path: test/helper/init.go
      linters:
        - gochecknoinits
    # TODO: Remove files from exclude below
    - path: test/util/nodes/nodes.go
      linters:
        - gochecknoinits
    - path: test/network/sriov/tests/init.go
      linters:
        - gochecknoinits
    - path: test/util/client/clients.go
      linters:
        - lll
    - path: test/cnf-tests/discovery/helper/helper.go
      linters:
        - lll
    - path: test/cnf-tests/discovery/tests/discovery.go
      linters:
        - lll
