package netmlbparameters

import (
	"net"

	"gitlab.cee.redhat.com/cnf/cnf-gotests/test/network/nethelper"

	k8sv1 "k8s.io/api/core/v1"
)

var (
	AddressPoolS1          = []string{"4.4.4.100", "4.4.4.101", "2001:4::100", "2001:4::101"}
	AddressPoolS2          = []string{"5.5.5.100", "5.5.5.101", "2001:5::100", "2001:5::101"}
	AddressPool1V6         = []string{"2001:4::100", "2001:4::101"}
	AddressPool2V6         = []string{"2001:5::100", "2001:5::101"}
	AddressPoolV6Prefix128 = []string{"2001:10:10::100", "2001:10:10::1000"}
	AddressPoolV6Prefix126 = []string{"2001:10:10::0"}
	AddressPoolV4Prefix32  = []string{"192.168.100.1", "192.168.100.240"}
	AddressPoolV4Prefix28  = []string{"192.168.100.0"}
	VtyshFRRCmdPrefix      = []string{"vtysh", "-u", "-c"}
)

const (
	// DaemonsConfigFile contains the frr daemons configuration file.
	DaemonsConfigFile = "daemons"
	DaemonsFile       = `
	# This file tells the frr package which daemons to start.
    #
    # Sample configurations for these daemons can be found in
    # /usr/share/doc/frr/examples/.
    #
    # ATTENTION:
    #
    # When activating a daemon for the first time, a config file, even if it is
    # empty, has to be present *and* be owned by the user and group "frr", else
    # the daemon will not be started by /etc/init.d/frr. The permissions should
    # be u=rw,g=r,o=.
    # When using "vtysh" such a config file is also needed. It should be owned by
    # group "frrvty" and set to ug=rw,o= though. Check /etc/pam.d/frr, too.
    #
    # The watchfrr, zebra and staticd daemons are always started.
    #
    bgpd=yes
    ospfd=no
    ospf6d=no
    ripd=no
    ripngd=no
    isisd=no
    pimd=no
    ldpd=no
    nhrpd=no
    eigrpd=no
    babeld=no
    sharpd=no
    pbrd=no
    bfdd=yes
    fabricd=no
    vrrpd=no
    pathd=no
    #
    # If this option is set the /etc/init.d/frr script automatically loads
    # the config via "vtysh -b" when the servers are started.
    # Check /etc/pam.d/frr if you intend to use "vtysh"!
    #
    vtysh_enable=yes
    zebra_options="  -A 127.0.0.1 -s 90000000"
    bgpd_options="   -A 127.0.0.1"
    ospfd_options="  -A 127.0.0.1"
    ospf6d_options=" -A ::1"
    ripd_options="   -A 127.0.0.1"
    ripngd_options=" -A ::1"
    isisd_options="  -A 127.0.0.1"
    pimd_options="   -A 127.0.0.1"
    ldpd_options="   -A 127.0.0.1"
    nhrpd_options="  -A 127.0.0.1"
    eigrpd_options=" -A 127.0.0.1"
    babeld_options=" -A 127.0.0.1"
    sharpd_options=" -A 127.0.0.1"
    pbrd_options="   -A 127.0.0.1"
    staticd_options="-A 127.0.0.1"
    bfdd_options="   -A 127.0.0.1"
    fabricd_options="-A 127.0.0.1"
    vrrpd_options="  -A 127.0.0.1"
    pathd_options="  -A 127.0.0.1"
    # configuration profile
    #
    #frr_profile="traditional"
    #frr_profile="datacenter"
    #
    # This is the maximum number of FD's that will be available.
    # Upon startup this is read by the control files and ulimit
    # is called.  Uncomment and use a reasonable value for your
    # setup if you are expecting a large number of peers in
    # say BGP.
    #MAX_FDS=1024
    # The list of daemons to watch is automatically generated by the init script.
    #watchfrr_options=""
    # To make watchfrr create/join the specified netns, use the following option:
    #watchfrr_options="--netns"
    # This only has an effect in /etc/frr/<somename>/daemons, and you need to
    # start FRR with "/usr/lib/frr/frrinit.sh start <somename>".
    # for debugging purposes, you can specify a "wrap" command to start instead
    # of starting the daemon directly, e.g. to use valgrind on ospfd:
    #   ospfd_wrap="/usr/bin/valgrind"
    # or you can use "all_wrap" for all daemons, e.g. to use perf record:
    #   all_wrap="/usr/bin/perf record --call-graph -"
    # the normal daemon command is added to this at the end.
	`
	BgpConfigTemplate = `
    debug bgp updates
    debug bgp neighbor
    debug bgp nht
    debug bfd peer

    log file /tmp/frr.log debugging
    log timestamp precision 3

    ipv6 nht resolve-via-default

    route-map RMAP permit 10
    set ipv6 next-hop prefer-global
    
    router bgp {{.LocalASN}}
      bgp router-id 10.10.10.10
      no bgp network import-check
      no bgp ebgp-requires-policy
      no bgp default ipv4-unicast
      neighbor {{.Addr1}} remote-as {{.ASN}}
      neighbor {{.Addr1}} password bgp-test
      neighbor {{.Addr2}} remote-as {{.ASN}}
      neighbor {{.Addr2}} password bgp-test
      neighbor {{.Addr3}} remote-as {{.ASN}}
      neighbor {{.Addr3}} password bgp-test
      neighbor {{.Addr4}} remote-as {{.ASN}}
      neighbor {{.Addr4}} password bgp-test
      address-family ipv4 unicast
        neighbor {{.Addr1}} activate
        neighbor {{.Addr2}} activate
        exit-address-family
      address-family ipv6 unicast
        neighbor {{.Addr3}} activate
        neighbor {{.Addr3}} route-map RMAP in
        neighbor {{.Addr4}} activate
        neighbor {{.Addr4}} route-map RMAP in
        exit-address-family
      end

    `

	BgpRoutePropagate = `
	debug bgp updates
	debug bgp neighbor
	debug bgp nht
	debug bfd peer
	
	log file /tmp/frr.log debugging
	log timestamp precision 3
	
	ipv6 nht resolve-via-default
	
	route-map RMAP permit 10
	set ipv6 next-hop prefer-global

	interface lo
	ip address 4.4.4.254/32

	router bgp 64500
	bgp router-id 10.10.10.10
	no bgp network import-check
	no bgp ebgp-requires-policy
	no bgp default ipv4-unicast
	neighbor {{.Addr1}} remote-as {{.ASN}}
	neighbor {{.Addr1}} password bgp-test
	neighbor {{.Addr2}} remote-as {{.ASN}}
	neighbor {{.Addr2}} password bgp-test
	neighbor {{.Addr3}} remote-as {{.ASN}}
	neighbor {{.Addr3}} password bgp-test
	neighbor {{.Addr4}} remote-as {{.ASN}}
	neighbor {{.Addr4}} password bgp-test
	address-family ipv4 unicast
	neighbor {{.Addr1}} activate
	neighbor {{.Addr2}} activate
	redistribute connected
	exit-address-family
	address-family ipv6 unicast
	neighbor {{.Addr3}} activate
	neighbor {{.Addr3}} route-map RMAP in
	neighbor {{.Addr4}} activate
	neighbor {{.Addr4}} route-map RMAP in
	redistribute connected
	exit-address-family
	end

	`

	ArgCommandNGINX      = "nginx && sleep INF"
	ArgCommandSCTPNGINX  = "nginx && /usr/bin/testcmd -listen -interface eth0 -port 50000 -protocol sctp"
	ArgCommandServerSCTP = "/usr/bin/testcmd -server %s -interface eth0 -port 50000 -protocol sctp"
)

type (
	NeighborConfig struct {
		LocalASN    uint32
		Addr1       string
		Addr2       string
		Addr3       string
		Addr4       string
		Password    string
		IPFamily    string
		ToAdvertise string
		BFDEnabled  bool
		MultiHop    bool
		ASN         uint32
	}
	Neighbor struct {
		IP          net.IP
		Connected   bool
		LocalAS     string
		RemoteAS    string
		UpdatesSent int
		PrefixSent  int
		Port        int
	}
	FRRInfo struct {
		PeerInfo map[string][]FRRNeighbor
	}
	FRRNeighbor struct {
		RemoteAs               int    `json:"remoteAs"`
		LocalAs                int    `json:"localAs"`
		BgpVersion             int    `json:"bgpVersion"`
		BgpState               string `json:"bgpState"`
		PortForeign            int    `json:"portForeign"`
		BgpHoldTimer           int    `json:"bgpTimerHoldTimeMsecs"`
		BgpKeepAlive           int    `json:"bgpTimerKeepAliveIntervalMsecs"`
		BgpConfiguredHoldTime  int    `json:"bgpTimerConfiguredHoldTimeMsecs"`
		BgpConfiguredKeepAlive int    `json:"bgpTimerConfiguredKeepAliveIntervalMsecs"`
		MessageStats           struct {
			UpdatesSent int `json:"updatesSent"`
		} `json:"messageStats"`
		AddressFamilyInfo map[string]struct {
			SentPrefixCounter     int `json:"sentPrefixCounter"`
			AcceptedPrefixCounter int `json:"acceptedPrefixCounter"`
		} `json:"addressFamilyInfo"`
	}
	Route struct {
		Destination *net.IPNet
		NextHops    []net.IP
		Prefix      string
		LocalPref   uint32
		PrefixLen   uint32
	}

	IPInfo struct {
		Routes map[string][]FRRRoute `json:"routes"`
	}

	FRRRoute struct {
		PeerID    string `json:"peerId"`
		Valid     bool   `json:"valid"`
		LocalPref uint32 `json:"locPrf"`
		Prefix    string `json:"prefix"`
		PrefixLen uint32 `json:"prefixLen"`
		Nexthops  []struct {
			IP    string `json:"ip"`
			Scope string `json:"scope"`
		} `json:"nexthops"`
	}

	MetallbTestParameters struct {
		TrafficPolicy string
		IPStack       string
	}

	MetallbPoolTestParameters struct {
		TrafficPolicy string `json:"TrafficPolicy,omitempty"`
		IPStack       string
		BGPASN        int   `json:"BGPASN,omitempty"`
		PrefixLenght  int32 `json:"PrefixLenght,omitempty"`
	}

	MetallbBFDTestParameters struct {
		BGPPeer       string
		IPStack       string
		TrafficPolicy k8sv1.ServiceExternalTrafficPolicyType
	}

	MetallbCRDTestParameters struct {
		TrafficPolicy k8sv1.ServiceExternalTrafficPolicyType
	}
)

// NewBGPTestParameters constructor for BGPTestParameters.
func NewBGPTestParameters(ipStack string, trafficPolicy string) (*MetallbTestParameters, error) {
	BGPTestParameters := new(MetallbTestParameters)
	err := nethelper.StrParamInListOfParams(ipStack, IPStackParameters)

	if err != nil {
		return nil, err
	}

	BGPTestParameters.IPStack = ipStack
	err = nethelper.StrParamInListOfParams(trafficPolicy, TrafficPolicies)

	if err != nil {
		return nil, err
	}

	BGPTestParameters.TrafficPolicy = trafficPolicy

	return BGPTestParameters, nil
}

// NewMetallbTestParameters constructor for Metallb TestParameters.
func NewMetallbTestParameters(ipStack string, bgpASN int, trafficPolicy string) (*MetallbPoolTestParameters, error) {
	BGPTestParameters := new(MetallbPoolTestParameters)
	err := nethelper.StrParamInListOfParams(ipStack, IPStackParameters)

	if err != nil {
		return nil, err
	}

	BGPTestParameters.IPStack = ipStack
	err = nethelper.StrParamInListOfParams(trafficPolicy, TrafficPolicies)

	if err != nil {
		return nil, err
	}

	BGPTestParameters.TrafficPolicy = trafficPolicy
	err = nethelper.IntParamInListOfParams(bgpASN, BGPASNParameters)

	if err != nil {
		return nil, err
	}

	BGPTestParameters.BGPASN = bgpASN

	return BGPTestParameters, nil
}

// NewMetallbCRDTestParameters constructor for MetallbCRDTestParameters.
func NewMetallbCRDTestParameters(externalTrafficPolicy k8sv1.ServiceExternalTrafficPolicyType) (
	*MetallbCRDTestParameters, error) {
	CRDTestParameters := new(MetallbCRDTestParameters)

	err := nethelper.StrParamInListOfParams(string(externalTrafficPolicy), TrafficPolicies)
	if err != nil {
		return nil, err
	}

	CRDTestParameters.TrafficPolicy = externalTrafficPolicy

	return CRDTestParameters, nil
}

// NewMetallbTestParamIPStack constructor for Metallb TestParameters.
func NewMetallbTestParamIPStack(ipStack string) (*MetallbPoolTestParameters, error) {
	BGPTestParameters := new(MetallbPoolTestParameters)
	err := nethelper.StrParamInListOfParams(ipStack, IPStackParameters)

	if err != nil {
		return nil, err
	}

	BGPTestParameters.IPStack = ipStack

	return BGPTestParameters, nil
}

// NewMetallbTestParamIPStackPrefix constructor for Metallb TestParameters.
func NewMetallbTestParamIPStackPrefix(ipStack string, prefixLenght int32) (*MetallbPoolTestParameters, error) {
	BGPTestParameters, err := NewMetallbTestParamIPStack(ipStack)

	if err != nil {
		return nil, err
	}

	BGPTestParameters.PrefixLenght = prefixLenght

	return BGPTestParameters, nil
}
