package netmlbparameters

import (
	"net"

	"gitlab.cee.redhat.com/cnf/cnf-gotests/test/network/nethelper"
)

var (
	AddressPoolS1 = []string{"4.4.4.100", "4.4.4.101", "2001:4::100", "2001:4::101"}
	AddressPoolS2 = []string{"5.5.5.100", "5.5.5.101", "2001:5::100", "2001:5::101"}
	AddressPoolV6 = []string{"2001:4::100", "2001:4::101"}
)

const (
	// BGPConfigFile contains the BGP router configuration file.
	BGPConfigFile = "bgpd.conf"
	// DaemonsConfigFile contains the frr daemons configuration file.
	DaemonsConfigFile = "daemons"
	DaemonsFile       = `
	# This file tells the frr package which daemons to start.
    #
    # Sample configurations for these daemons can be found in
    # /usr/share/doc/frr/examples/.
    #
    # ATTENTION:
    #
    # When activating a daemon for the first time, a config file, even if it is
    # empty, has to be present *and* be owned by the user and group "frr", else
    # the daemon will not be started by /etc/init.d/frr. The permissions should
    # be u=rw,g=r,o=.
    # When using "vtysh" such a config file is also needed. It should be owned by
    # group "frrvty" and set to ug=rw,o= though. Check /etc/pam.d/frr, too.
    #
    # The watchfrr, zebra and staticd daemons are always started.
    #
    bgpd=yes
    ospfd=no
    ospf6d=no
    ripd=no
    ripngd=no
    isisd=no
    pimd=no
    ldpd=no
    nhrpd=no
    eigrpd=no
    babeld=no
    sharpd=no
    pbrd=no
    bfdd=yes
    fabricd=no
    vrrpd=no
    pathd=no
    #
    # If this option is set the /etc/init.d/frr script automatically loads
    # the config via "vtysh -b" when the servers are started.
    # Check /etc/pam.d/frr if you intend to use "vtysh"!
    #
    vtysh_enable=yes
    zebra_options="  -A 127.0.0.1 -s 90000000"
    bgpd_options="   -A 127.0.0.1"
    ospfd_options="  -A 127.0.0.1"
    ospf6d_options=" -A ::1"
    ripd_options="   -A 127.0.0.1"
    ripngd_options=" -A ::1"
    isisd_options="  -A 127.0.0.1"
    pimd_options="   -A 127.0.0.1"
    ldpd_options="   -A 127.0.0.1"
    nhrpd_options="  -A 127.0.0.1"
    eigrpd_options=" -A 127.0.0.1"
    babeld_options=" -A 127.0.0.1"
    sharpd_options=" -A 127.0.0.1"
    pbrd_options="   -A 127.0.0.1"
    staticd_options="-A 127.0.0.1"
    bfdd_options="   -A 127.0.0.1"
    fabricd_options="-A 127.0.0.1"
    vrrpd_options="  -A 127.0.0.1"
    pathd_options="  -A 127.0.0.1"
    # configuration profile
    #
    #frr_profile="traditional"
    #frr_profile="datacenter"
    #
    # This is the maximum number of FD's that will be available.
    # Upon startup this is read by the control files and ulimit
    # is called.  Uncomment and use a reasonable value for your
    # setup if you are expecting a large number of peers in
    # say BGP.
    #MAX_FDS=1024
    # The list of daemons to watch is automatically generated by the init script.
    #watchfrr_options=""
    # To make watchfrr create/join the specified netns, use the following option:
    #watchfrr_options="--netns"
    # This only has an effect in /etc/frr/<somename>/daemons, and you need to
    # start FRR with "/usr/lib/frr/frrinit.sh start <somename>".
    # for debugging purposes, you can specify a "wrap" command to start instead
    # of starting the daemon directly, e.g. to use valgrind on ospfd:
    #   ospfd_wrap="/usr/bin/valgrind"
    # or you can use "all_wrap" for all daemons, e.g. to use perf record:
    #   all_wrap="/usr/bin/perf record --call-graph -"
    # the normal daemon command is added to this at the end.
	`
	BgpConfigTemplate = `
    debug bgp updates
    debug bgp neighbor
    debug bgp nht
    debug bfd peer

    log file /tmp/frr.log debugging
    log timestamp precision 3

    ipv6 nht resolve-via-default

    route-map RMAP permit 10
    set ipv6 next-hop prefer-global
    
    router bgp 64500
      bgp router-id 10.10.10.10
      no bgp network import-check
      no bgp ebgp-requires-policy
      no bgp default ipv4-unicast
      neighbor {{.Addr1}} remote-as {{.ASN}}
      neighbor {{.Addr1}} password bgp-test
      neighbor {{.Addr2}} remote-as {{.ASN}}
      neighbor {{.Addr2}} password bgp-test
      neighbor {{.Addr3}} remote-as {{.ASN}}
      neighbor {{.Addr3}} password bgp-test
      neighbor {{.Addr4}} remote-as {{.ASN}}
      neighbor {{.Addr4}} password bgp-test
      address-family ipv4 unicast
        neighbor {{.Addr1}} activate
        neighbor {{.Addr2}} activate
        exit-address-family
      address-family ipv6 unicast
        neighbor {{.Addr3}} activate
        neighbor {{.Addr3}} route-map RMAP in
        neighbor {{.Addr4}} activate
        neighbor {{.Addr4}} route-map RMAP in
        exit-address-family
      end

    `
)

type (
	NeighborConfig struct {
		Addr1       string
		Addr2       string
		Addr3       string
		Addr4       string
		Password    string
		IPFamily    string
		ToAdvertise string
		BFDEnabled  bool
		MultiHop    bool
		ASN         uint32
	}
	Neighbor struct {
		IP          net.IP
		Connected   bool
		LocalAS     string
		RemoteAS    string
		UpdatesSent int
		PrefixSent  int
		Port        int
	}
	FRRNeighbor struct {
		RemoteAs     int    `json:"remoteAs"`
		LocalAs      int    `json:"localAs"`
		BgpVersion   int    `json:"bgpVersion"`
		BgpState     string `json:"bgpState"`
		PortForeign  int    `json:"portForeign"`
		MessageStats struct {
			UpdatesSent int `json:"updatesSent"`
		} `json:"messageStats"`
		AddressFamilyInfo map[string]struct {
			SentPrefixCounter int `json:"sentPrefixCounter"`
		} `json:"addressFamilyInfo"`
	}
	Route struct {
		Destination *net.IPNet
		NextHops    []net.IP
		LocalPref   uint32
	}

	IPInfo struct {
		Routes map[string][]FRRRoute `json:"routes"`
	}

	FRRRoute struct {
		PeerID    string `json:"peerId"`
		Valid     bool   `json:"valid"`
		LocalPref uint32 `json:"locPrf"`
		Nexthops  []struct {
			IP    string `json:"ip"`
			Scope string `json:"scope"`
		} `json:"nexthops"`
	}

	MetallbTestParameters struct {
		TrafficPolicy string
		IPStack       string
	}
)

// NewBGPTestParameters constructor for BGPTestParameters.
func NewBGPTestParameters(ipStack string, trafficPolicy string) (*MetallbTestParameters, error) {
	BGPTestParameters := new(MetallbTestParameters)
	err := nethelper.StrParamInListOfParams(ipStack, IPStackParameters)

	if err != nil {
		return nil, err
	}

	BGPTestParameters.IPStack = ipStack
	err = nethelper.StrParamInListOfParams(trafficPolicy, TrafficPolicies)

	if err != nil {
		return nil, err
	}

	BGPTestParameters.TrafficPolicy = trafficPolicy

	return BGPTestParameters, nil
}
