# General configurations
general:
  report: reports/
  cnf_worker_label: "node-role.kubernetes.io/worker-cnf"
  failed_tests_logs: "failed_tests_logs.txt"
network:
  test_container_image: quay.io/ocp-edge-qe/cnf-gotests-client:v4.10
  frr_image: quay.io/ocp-edge-qe/frr:stable_7.5
ran:
  cnf_test_image: quay.io/openshift-kni/cnf-tests:4.8
  stressng_test_image: quay.io/ocp-edge-qe/stress-ng:2.0
  oslat_test_image: quay.io/ocp-edge-qe/oslat:latest
  process_exporter_image: quay.io/ocp-edge-qe/process-exporter:ppid-2
  process_exporter_resources: test/ran/resources/process-exporter/
  bmc_user: root
  bmc_password: calvin
