# General configurations
general:
  report: reports/
  cnf_worker_label: "node-role.kubernetes.io/worker-cnf"
  failed_tests_logs: "failed_tests_logs.txt"
network:
  test_container_image: quay.io/ocp-edge-qe/cnf-gotests-client:v4.15
  frr_image: quay.io/ocp-edge-qe/frr:stable_7.5
  switch_lag_names: "ae0,ae1"
ran:
  cnf_test_image: quay.io/openshift-kni/cnf-tests:4.8
  stressng_test_image: quay.io/container-perf-tools/stress-ng:latest
  oslat_test_image: quay.io/container-perf-tools/oslat:latest
  process_exporter_image: quay.io/ocp-edge-qe/process-exporter:ppid-2
  process_exporter_resources: test/ran/resources/process-exporter/
  consumer_image: quay.io/redhat-cne/cloud-event-consumer:latest
  bmc_user: root
  bmc_password: calvin
  bmer_consumer_manifests: ../resources/bmer-preconsumer/
  ptp_consumer_manifests: ../resources/ptp-preconsumer/
  talm_precache_policies:
    - common-config-policy
    - common-subscriptions-policy
  ocp_upgrade_upstream_url: "https://api.openshift.com/api/upgrades_info/v1/graph"
  workload_repository: https://github.com/openshift-kni/du-intensive.git
  workload_version: v1.0
  workload_create: du-intensive.yaml
  workload_remove: du-intensive-remove.yaml
  workload_registry: quay.io/rh_ee_apalanis
