package tests

import (
	"bytes"
	"context"
	"fmt"
	"log"
	"strings"
	"time"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	performancev2 "github.com/openshift/cluster-node-tuning-operator/pkg/apis/performanceprofile/v2"
	tunedv1 "github.com/openshift/cluster-node-tuning-operator/pkg/apis/tuned/v1"
	mcv1 "github.com/openshift/machine-config-operator/pkg/apis/machineconfiguration.openshift.io/v1"
	"github.com/tidwall/gjson"
	"gitlab.cee.redhat.com/cnf/cnf-gotests/test/helper"
	"gitlab.cee.redhat.com/cnf/cnf-gotests/test/parameters"
	"gitlab.cee.redhat.com/cnf/cnf-gotests/test/ran/cpu/rancpuhelper"
	"gitlab.cee.redhat.com/cnf/cnf-gotests/test/ran/ranhelper"
	"gitlab.cee.redhat.com/cnf/cnf-gotests/test/ran/workloadpartitioning/ranwphelper"
	"gitlab.cee.redhat.com/cnf/cnf-gotests/test/ran/ztp/ranztphelper"
	"gitlab.cee.redhat.com/cnf/cnf-gotests/test/ran/ztp/ranztpparameters"
	testClient "gitlab.cee.redhat.com/cnf/cnf-gotests/test/util/client"
	mcp "gitlab.cee.redhat.com/cnf/cnf-gotests/test/util/machineconfigpool"
	"gitlab.cee.redhat.com/cnf/cnf-gotests/test/util/namespaces"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/kubernetes/pkg/kubelet/cm/cpuset"
	goclient "sigs.k8s.io/controller-runtime/pkg/client"
)

func waitForMcpUpdate(clientSet *testClient.ClientSet, mcpName string) error {
	if clientSet == nil {
		return fmt.Errorf("clientSet is undefined")
	}

	if len(strings.TrimSpace(mcpName)) == 0 {
		return fmt.Errorf("machine config name is undefined")
	}

	// waits for updating transition
	log.Println("Waiting for updating transition")

	err := mcp.WaitForCondition(
		clientSet,
		&mcv1.MachineConfigPool{ObjectMeta: metav1.ObjectMeta{Name: mcpName}},
		mcv1.MachineConfigPoolUpdating,
		10*time.Minute)

	if err != nil {
		return err
	}
	// waits for updated transition
	machineCP := &mcv1.MachineConfigPool{}
	err = clientSet.Get(context.TODO(), goclient.ObjectKey{Name: mcpName}, machineCP)

	if err != nil {
		return err
	}

	log.Println("Waiting for updated transition")

	err = mcp.WaitForCondition(
		clientSet,
		&mcv1.MachineConfigPool{ObjectMeta: metav1.ObjectMeta{Name: mcpName}},
		mcv1.MachineConfigPoolUpdated,
		time.Duration(60*machineCP.Status.MachineCount)*time.Minute)

	return err
}

var _ = Describe("ZTP workload partitioning tests", Ordered, Label("ztp-workload-partitioning"), func() {
	var (
		snoNode         *corev1.Node
		perfProfile     *performancev2.PerformanceProfile
		machineConfigWP = mcv1.MachineConfig{}
		tuned           = tunedv1.Tuned{}
		tunedPatch      = tunedv1.Tuned{}
		selectorByName  = func(p *performancev2.PerformanceProfile) bool { return p.Name == ranztpparameters.PerfProfileName }
	)

	BeforeAll(func() {

		// ensure a specific performance profile generated by ZTP
		perfProfile, _ = rancpuhelper.GetPerformanceProfileWithCPUSet(selectorByName)
		if perfProfile == nil {
			Skip(fmt.Sprintf("No performance profile %s found on cluster", ranztpparameters.PerfProfileName))
		}

		// ensure a specific machine config generated by ZTP
		err := ranztphelper.SpokeAPIClient.Get(context.TODO(),
			goclient.ObjectKey{Name: ranztpparameters.MachineConfigName}, &machineConfigWP)
		if err != nil {
			Skip(fmt.Sprintf("No machineconfig %s found on cluster", ranztpparameters.MachineConfigName))
		}

		// ensure specific tuned generated by ZTP
		err = ranztphelper.SpokeAPIClient.Get(context.TODO(),
			types.NamespacedName{Name: ranztpparameters.TunedName, Namespace: ranztpparameters.TunedNamespace}, &tuned)
		if err != nil {
			Skip(fmt.Sprintf("No tuned %s on namespace %s found on cluster", ranztpparameters.TunedName,
				ranztpparameters.TunedNamespace))
		}

		err = ranztphelper.SpokeAPIClient.Get(context.TODO(),
			types.NamespacedName{Name: ranztpparameters.TunedPatchName, Namespace: ranztpparameters.TunedNamespace}, &tunedPatch)
		if err != nil {
			Skip(fmt.Sprintf("No tuned %s on namespace %s found on cluster", ranztpparameters.TunedPatchName,
				ranztpparameters.TunedNamespace))
		}

		// get SNO
		nodeList, err := ranhelper.GetSnoNodes()
		if err != nil {
			Skip("This test only applies to SNO clusters")
		}
		snoNode = nodeList[0]

		// create a helper pod to run commands on nodes
		log.Println("Setup initiated: creating a privileged pod")
		helper.CreatePrivilegedPods("")
	})

	AfterEach(func() {
		// Reset the policies app back to default after each test
		By("Resetting the policies app back to the original settings", func() {
			err := ranztphelper.SetGitDetailsInArcgocd(
				ranztphelper.ArgocdApps[ranztpparameters.ArgocdPoliciesAppName].Repo,
				ranztphelper.ArgocdApps[ranztpparameters.ArgocdPoliciesAppName].Branch,
				ranztphelper.ArgocdApps[ranztpparameters.ArgocdPoliciesAppName].Path,
				ranztpparameters.ArgocdPoliciesAppName,
				true,
				false,
			)
			Expect(err).ToNot(HaveOccurred())
		})

		By("waiting for the change to take effect", func() {
			log.Println("Sleeping to wait for changes to take effect")
			time.Sleep(1 * time.Minute)
		})

		By("restoring original config for workload partitioning", func() {

			machineConfigWPTmp := mcv1.MachineConfig{}
			log.Printf("restoring machine config: %s", ranztpparameters.MachineConfigName)
			err := ranztphelper.SpokeAPIClient.Get(context.TODO(),
				goclient.ObjectKey{Name: ranztpparameters.MachineConfigName}, &machineConfigWPTmp)
			Expect(err).ToNot(HaveOccurred())

			machineConfigWPTmp.Spec = machineConfigWP.Spec
			err = ranztphelper.SpokeAPIClient.Update(context.TODO(), &machineConfigWPTmp)
			Expect(err).ToNot(HaveOccurred())
			// reboot expected
			err = ranztphelper.CheckNodeIsFunctionalAfterMCchanges(ranztpparameters.MCPname, waitForMcpUpdate)
			Expect(err).ToNot(HaveOccurred())

			log.Printf("restoring performance profile: %s", ranztpparameters.PerfProfileName)
			perfProfileTmp, _ := rancpuhelper.GetPerformanceProfileWithCPUSet(selectorByName)
			Expect(perfProfileTmp).NotTo(BeNil())
			perfProfileTmp.Spec = perfProfile.Spec
			err = ranztphelper.SpokeAPIClient.Update(context.TODO(), perfProfileTmp)
			Expect(err).ToNot(HaveOccurred())
			// reboot expected
			err = ranztphelper.CheckNodeIsFunctionalAfterMCchanges(ranztpparameters.MCPname, waitForMcpUpdate)
			Expect(err).ToNot(HaveOccurred())

			log.Printf("restoring tuned: %s", ranztpparameters.TunedName)
			tunedTmp := tunedv1.Tuned{}
			err = ranztphelper.SpokeAPIClient.Get(context.TODO(),
				types.NamespacedName{Name: ranztpparameters.TunedName, Namespace: ranztpparameters.TunedNamespace}, &tunedTmp)
			Expect(err).ToNot(HaveOccurred())
			tunedTmp.Spec = tuned.Spec
			err = ranztphelper.SpokeAPIClient.Update(context.TODO(), &tunedTmp)
			Expect(err).ToNot(HaveOccurred())

			log.Printf("restoring tuned: %s", ranztpparameters.TunedPatchName)
			err = ranztphelper.SpokeAPIClient.Get(context.TODO(),
				types.NamespacedName{Name: ranztpparameters.TunedPatchName, Namespace: ranztpparameters.TunedNamespace}, &tunedTmp)
			Expect(err).ToNot(HaveOccurred())
			tunedTmp.Spec = tunedPatch.Spec
			err = ranztphelper.SpokeAPIClient.Update(context.TODO(), &tunedTmp)
			Expect(err).ToNot(HaveOccurred())
			// reboot expected
			err = ranztphelper.CheckNodeIsFunctionalAfterMCchanges(ranztpparameters.MCPname, waitForMcpUpdate)
			Expect(err).ToNot(HaveOccurred())

		})
	})

	AfterAll(func() {
		// delete helper pod
		log.Println("Teardown initiated: deleting privileged pod")
		err := namespaces.DeleteAndWait(helper.Apiclient, parameters.PrivPodNamespace, 10*time.Minute)
		Expect(err).ToNot(HaveOccurred())
	})

	Context("when a ZTP configuration updates the cpu partitioning", Label("ztp-update-workload-partitioning"), func() {
		// https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-54235

		It("should update cpu partitioning with the new reserved cpus on spoke", func() {

			// The ztp test data is stored in a nested directory within the ztp repo
			testGitPath := ranztphelper.ArgocdApps[ranztpparameters.ArgocdPoliciesAppName].Path +
				"/ztp-test/workload-partitioning"

			By("Updating ArgoCD policies app", func() {
				// Update the Argo app to point to the new test kustomization
				err := ranztphelper.SetGitDetailsInArcgocd(
					ranztphelper.ArgocdApps[ranztpparameters.ArgocdPoliciesAppName].Repo,
					ranztphelper.ArgocdApps[ranztpparameters.ArgocdPoliciesAppName].Branch,
					testGitPath,
					ranztpparameters.ArgocdPoliciesAppName,
					true,
					true,
				)
				Expect(err).ToNot(HaveOccurred())
			})

			By("Waiting for policies to be created", func() {
				err := ranztphelper.WaitForPolicyToExist(
					"test-sno-1-new-cpu-partitioning-config-policy",
					ranztpparameters.ZtpTestNamespace,
					5*time.Minute,
				)
				Expect(err).ToNot(HaveOccurred())
			})

			By("waiting for SNO to be functional again after rebooting due to configuration changes", func() {
				// reboot expected
				err := ranztphelper.CheckNodeIsFunctionalAfterMCchanges(ranztpparameters.MCPname, waitForMcpUpdate)
				Expect(err).ToNot(HaveOccurred())
			})

			// get performance profile after ArgoCD PGT update
			pp, err := rancpuhelper.GetPerformanceProfileWithCPUSet(selectorByName)
			Expect(err).ToNot(HaveOccurred())

			reservedCPUSet := cpuset.MustParse(string(*pp.Spec.CPU.Reserved))

			By("Checking kubeletconfig reservedSystemCPUs on SNO", func() {

				// oc get kubeletconfigs.machineconfiguration.openshift.io performance-openshift-node-performance-profile
				kubeletconfig := mcv1.KubeletConfig{}
				err := ranztphelper.SpokeAPIClient.Get(context.TODO(),
					goclient.ObjectKey{Name: "performance-openshift-node-performance-profile"}, &kubeletconfig)
				Expect(err).ToNot(HaveOccurred())

				// from bytes to json
				jsonBytes, err := kubeletconfig.Spec.KubeletConfig.Marshal()
				Expect(err).ToNot(HaveOccurred())

				// from json to string
				jsonString := bytes.NewBuffer(jsonBytes).String()

				reservedSystemCPUs := gjson.Get(jsonString, "reservedSystemCPUs").String()
				Expect(reservedSystemCPUs == reservedCPUSet.String())
			})

			By("Checking cpuset for all running containers via crictl inspect on SNO", func() {
				containersInfo := ranwphelper.GetContainersInfo(snoNode)
				ranwphelper.CheckPodsAffinity(ranwphelper.GetMgmtContainersInfo(containersInfo), reservedCPUSet)
			})

			By("checking OS daemon pinned to reserved cpus on SNO", func() {
				failedPids, _ := ranwphelper.CheckCPUAffinityOnNonKernelPids(snoNode, reservedCPUSet)
				Expect(failedPids).To(BeEmpty())
			})

			By("Checking new cpu processes affinities on SNO", func() {

				log.Printf("reservedCPUSet on Performance profile: %s\n", reservedCPUSet)

				processNames := []string{"crio", "kubelet", "ovn"}
				err := ranztphelper.CheckAffinitiesByProcessMatch(snoNode, processNames, reservedCPUSet.String())
				Expect(err).ToNot(HaveOccurred())
			})

		})
	})
})
