package tests

import (
	"bytes"
	"context"
	"fmt"
	"log"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	performancev2 "github.com/openshift/cluster-node-tuning-operator/pkg/apis/performanceprofile/v2"
	tunedv1 "github.com/openshift/cluster-node-tuning-operator/pkg/apis/tuned/v1"
	mcv1 "github.com/openshift/machine-config-operator/pkg/apis/machineconfiguration.openshift.io/v1"
	"github.com/tidwall/gjson"
	"gitlab.cee.redhat.com/cnf/cnf-gotests/test/ran/cpu/rancpuhelper"
	"gitlab.cee.redhat.com/cnf/cnf-gotests/test/ran/ranhelper"
	"gitlab.cee.redhat.com/cnf/cnf-gotests/test/ran/talm/rantalmhelper"
	"gitlab.cee.redhat.com/cnf/cnf-gotests/test/ran/workloadpartitioning/ranwphelper"
	"gitlab.cee.redhat.com/cnf/cnf-gotests/test/ran/ztp/ranztphelper"
	"gitlab.cee.redhat.com/cnf/cnf-gotests/test/ran/ztp/ranztpparameters"
	testClient "gitlab.cee.redhat.com/cnf/cnf-gotests/test/util/client"
	"gitlab.cee.redhat.com/cnf/cnf-gotests/test/util/polarion"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/kubernetes/pkg/kubelet/cm/cpuset"
	policiesv1 "open-cluster-management.io/governance-policy-propagator/api/v1"
	goclient "sigs.k8s.io/controller-runtime/pkg/client"
)

func validateWorkloadPartition(snoNode *corev1.Node, selector rancpuhelper.SelectorFunc) {
	// get performance profile after ArgoCD PGT update
	pp, err := rancpuhelper.GetPerformanceProfileWithCPUSet(selector)
	Expect(err).ToNot(HaveOccurred())

	reservedCPUSet := cpuset.MustParse(string(*pp.Spec.CPU.Reserved))
	log.Printf("reservedCPUSet on Performance profile: %s\n", reservedCPUSet)

	By("Checking kubeletconfig reservedSystemCPUs on SNO", func() {

		// oc get kubeletconfigs.machineconfiguration.openshift.io performance-openshift-node-performance-profile
		kubeletconfig := mcv1.KubeletConfig{}
		err := ranztphelper.SpokeAPIClient.Get(context.Background(),
			goclient.ObjectKey{Name: "performance-openshift-node-performance-profile"}, &kubeletconfig)
		Expect(err).ToNot(HaveOccurred())

		// from bytes to json
		jsonBytes, err := kubeletconfig.Spec.KubeletConfig.Marshal()
		Expect(err).ToNot(HaveOccurred())

		// from json to string
		jsonString := bytes.NewBuffer(jsonBytes).String()

		reservedSystemCPUs := gjson.Get(jsonString, "reservedSystemCPUs").String()
		Expect(reservedSystemCPUs == reservedCPUSet.String())
	})

	By("Checking new cpu processes affinities on SNO", func() {
		processNames := []string{"crio", "kubelet", "ovn"}
		err := ranztphelper.CheckAffinitiesByProcessMatch(snoNode, processNames, reservedCPUSet)
		Expect(err).ToNot(HaveOccurred())
	})

	By("Checking cpuset for all running containers via crictl inspect on SNO", func() {
		containersInfo := ranwphelper.GetContainersInfo(snoNode)
		ranwphelper.CheckPodsAffinity(ranwphelper.GetMgmtContainersInfo(containersInfo), reservedCPUSet)
	})

	By("checking OS daemon pinned to reserved cpus on SNO", func() {
		failedPids, _ := ranwphelper.CheckCPUAffinityOnNonKernelPids(snoNode, reservedCPUSet)
		Expect(failedPids).To(BeEmpty())
	})
}

var _ = Describe("ZTP workload partitioning tests", Ordered, Label("ztp-workload-partitioning"), func() {
	// These tests use the hub and spoke
	var clusterList []*testClient.ClientSet
	var (
		snoNode         *corev1.Node
		perfProfile     *performancev2.PerformanceProfile
		machineConfigWP *mcv1.MachineConfig
		tunedPatch      *tunedv1.Tuned
		selectorByName  = func(p *performancev2.PerformanceProfile) bool { return p.Name == ranztpparameters.PerfProfileName }
	)

	BeforeAll(func() {
		// Initialize cluster list
		clusterList = ranztphelper.GetAllTestClients()
	})

	BeforeEach(func() {
		// Check that the required clusters are present
		By("Checking that required clusters are present", func() {
			err := ranhelper.IsClustersPresent(clusterList)
			if err != nil {
				Skip(fmt.Sprintf("error occurred validating required clusters are present: %s", err.Error()))
			}
		})

		// Check for minimum ztp version
		By("Checking the ZTP version", func() {
			if !ranhelper.IsVersionStringInRange(
				ranztphelper.ZtpVersion,
				"4.12",
				"",
			) {
				Skip(fmt.Sprintf(
					"unable to run test on ztp version '%s' as it is less than minimum '%s",
					ranztphelper.ZtpVersion,
					"4.12",
				))
			}
		})

		// ensure a specific performance profile generated by ZTP
		perfProfile, _ = rancpuhelper.GetPerformanceProfileWithCPUSet(selectorByName)
		if perfProfile == nil {
			Skip(fmt.Sprintf("No performance profile %s found on cluster", ranztpparameters.PerfProfileName))
		}

		// ensure a specific machine config generated by ZTP
		machineConfigWP = &mcv1.MachineConfig{}
		err := ranztphelper.SpokeAPIClient.Get(context.Background(),
			goclient.ObjectKey{Name: ranztpparameters.MachineConfigName}, machineConfigWP)
		if err != nil {
			Skip(fmt.Sprintf("No machineconfig %s found on cluster", ranztpparameters.MachineConfigName))
		}

		// ensure specific tuned generated by ZTP
		tunedPatch = &tunedv1.Tuned{}
		err = ranztphelper.SpokeAPIClient.Get(context.Background(),
			types.NamespacedName{Name: ranztpparameters.TunedPatchName, Namespace: ranztpparameters.TunedNamespace}, tunedPatch)
		if err != nil {
			Skip(fmt.Sprintf("No tuned %s on namespace %s found on cluster", ranztpparameters.TunedPatchName,
				ranztpparameters.TunedNamespace))
		}

		// get SNO
		nodeList, err := ranhelper.GetSnoNodes()
		if err != nil {
			Skip("This test only applies to SNO clusters")
		}
		snoNode = nodeList[0]
	})

	AfterEach(func() {
		// Reset the policies app back to default after each test
		By("Resetting the policies app back to the original settings", func() {
			err := ranztphelper.SetGitDetailsInArcgocd(
				ranztphelper.ArgocdApps[ranztpparameters.ArgocdPoliciesAppName].Repo,
				ranztphelper.ArgocdApps[ranztpparameters.ArgocdPoliciesAppName].Branch,
				ranztphelper.ArgocdApps[ranztpparameters.ArgocdPoliciesAppName].Path,
				ranztpparameters.ArgocdPoliciesAppName,
				true,
				true,
			)
			Expect(err).ToNot(HaveOccurred())
		})

		By("Removing the cgu if it exists", func() {
			err := rantalmhelper.DeleteCguAndWait(
				ranztphelper.HubAPIClient,
				"workload-partition-update",
				ranztpparameters.ZtpTestNamespace,
			)
			Expect(err).ToNot(HaveOccurred())
		})

		By("restoring original config for workload partitioning", func() {
			if machineConfigWP == nil || perfProfile == nil || tunedPatch == nil {
				Skip("No need to restore workload parititoning")
			}

			// Get the current performanceprofile
			perfProfileTmp, _ := rancpuhelper.GetPerformanceProfileWithCPUSet(selectorByName)
			Expect(perfProfileTmp).NotTo(BeNil())

			// Get the current tuned patch
			tunedTmp := tunedv1.Tuned{}
			err := ranztphelper.SpokeAPIClient.Get(context.Background(),
				types.NamespacedName{Name: ranztpparameters.TunedPatchName, Namespace: ranztpparameters.TunedNamespace}, &tunedTmp)
			Expect(err).ToNot(HaveOccurred())

			// Get the current MC
			machineConfigWPTmp := mcv1.MachineConfig{}
			err = ranztphelper.SpokeAPIClient.Get(context.Background(),
				goclient.ObjectKey{Name: ranztpparameters.MachineConfigName}, &machineConfigWPTmp)
			Expect(err).ToNot(HaveOccurred())

			// Update performanceprofile back to original setting
			log.Printf("restoring performance profile: %s", ranztpparameters.PerfProfileName)
			perfProfileTmp.Spec = perfProfile.Spec
			if perfProfile.GetAnnotations() != nil {
				perfProfileTmp.SetAnnotations(perfProfile.Annotations)
			}
			if perfProfile.GetLabels() != nil {
				perfProfileTmp.SetLabels(perfProfile.Labels)
			}
			err = ranztphelper.SpokeAPIClient.Update(context.Background(), perfProfileTmp)
			Expect(err).ToNot(HaveOccurred())

			// Update tuned patch back to original setting
			log.Printf("restoring tuned: %s", ranztpparameters.TunedPatchName)
			tunedTmp.Spec = tunedPatch.Spec
			if tunedPatch.GetAnnotations() != nil {
				tunedTmp.SetAnnotations(tunedPatch.Annotations)
			}
			if tunedPatch.GetLabels() != nil {
				tunedTmp.SetLabels(tunedPatch.Labels)
			}
			err = ranztphelper.SpokeAPIClient.Update(context.Background(), &tunedTmp)
			Expect(err).ToNot(HaveOccurred())

			// Update MC back to original setting
			log.Printf("restoring machine config: %s", ranztpparameters.MachineConfigName)
			machineConfigWPTmp.Spec = machineConfigWP.Spec
			if machineConfigWP.GetAnnotations() != nil {
				machineConfigWPTmp.SetAnnotations(machineConfigWP.Annotations)
			}
			if machineConfigWP.GetLabels() != nil {
				machineConfigWPTmp.SetLabels(machineConfigWP.Labels)
			}
			err = ranztphelper.SpokeAPIClient.Update(context.Background(), &machineConfigWPTmp)
			Expect(err).ToNot(HaveOccurred())

			// reboots expected
			err = ranztphelper.CheckNodeIsFunctionalAfterMCchanges(
				ranztphelper.SpokeAPIClient, ranztpparameters.MCPname)
			Expect(err).ToNot(HaveOccurred())

			// Make sure the workload partition updates are reverted back to the original setting
			validateWorkloadPartition(snoNode, selectorByName)
		})
	})

	Context("when a ZTP configuration updates the cpu partitioning", Label("ztp-update-workload-partitioning"), func() {
		// https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-54235

		wpPolicyName := "cpu-partitioning-policy-config" // inform policy

		It("should update cpu partitioning with the new reserved cpus on spoke", polarion.ID("54235"), func() {

			// The ztp test data is stored in a nested directory within the ztp repo
			testGitPath := ranztphelper.ArgocdApps[ranztpparameters.ArgocdPoliciesAppName].Path +
				"/ztp-test/workload-partitioning"

			By("Checking if the git path exists", func() {
				if !ranztphelper.DoesGitPathExist(
					ranztphelper.ArgocdApps[ranztpparameters.ArgocdPoliciesAppName].Repo,
					ranztphelper.ArgocdApps[ranztpparameters.ArgocdPoliciesAppName].Branch,
					testGitPath+"/kustomization.yaml",
				) {
					Skip(fmt.Sprintf("git path '%s' could not be found", testGitPath))
				}
			})

			By("Updating ArgoCD policies app", func() {
				// Update the Argo app to point to the new test kustomization
				err := ranztphelper.SetGitDetailsInArcgocd(
					ranztphelper.ArgocdApps[ranztpparameters.ArgocdPoliciesAppName].Repo,
					ranztphelper.ArgocdApps[ranztpparameters.ArgocdPoliciesAppName].Branch,
					testGitPath,
					ranztpparameters.ArgocdPoliciesAppName,
					true,
					true,
				)
				Expect(err).ToNot(HaveOccurred())
			})

			By("Waiting for policies to be created", func() {
				err := ranztphelper.WaitForPolicyToExist(
					wpPolicyName,
					ranztpparameters.ZtpTestNamespace,
					ranztpparameters.ArgocdChangeTimeout,
				)
				Expect(err).ToNot(HaveOccurred())
			})

			By("Validating the policy reaches NonCompliant status", func() {
				err := ranztphelper.WaitForPolicyToHaveComplianceState(
					wpPolicyName,
					ranztpparameters.ZtpTestNamespace,
					policiesv1.NonCompliant,
					ranztpparameters.ArgocdChangeTimeout,
				)
				Expect(err).ToNot(HaveOccurred())
			})

			By("Creating CGU to apply the changes", func() {
				cgu := rantalmhelper.GetCguDefinition(
					"workload-partition-update",
					[]string{
						ranztphelper.SpokeName,
					},
					[]string{},
					[]string{
						wpPolicyName,
					},
					ranztpparameters.ZtpTestNamespace,
					1,
					10,
				)

				// Make sure cgu is enabled
				cgu.Spec.Enable = rantalmhelper.BoolAddr(true)

				// Create the cgu
				err := rantalmhelper.CreateCguAndWait(
					ranztphelper.HubAPIClient,
					cgu,
				)

				Expect(err).ToNot(HaveOccurred())
			})

			By("waiting for SNO to be functional again after rebooting due to the changes", func() {
				// reboots expected
				err := ranztphelper.CheckNodeIsFunctionalAfterMCchanges(
					ranztphelper.SpokeAPIClient, ranztpparameters.MCPname)
				Expect(err).ToNot(HaveOccurred())
			})

			// Validate the workload partitioning updates
			validateWorkloadPartition(snoNode, selectorByName)
		})
	})
})
